// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cosmos/ibc-apps/middleware/packet-forward-middleware/v7/packetforward/types (interfaces: TransferMiddlewareKeeper)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	types "github.com/cosmos/cosmos-sdk/types"
	gomock "go.uber.org/mock/gomock"

	pcktfrwdtypes "github.com/cosmos/ibc-apps/middleware/packet-forward-middleware/v7/packetforward/types"
)

// MockTransferMiddlewareKeeper is a mock of TransferMiddlewareKeeper interface.
type MockTransferMiddlewareKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockTransferMiddlewareKeeperMockRecorder
}

// MockTransferMiddlewareKeeperMockRecorder is the mock recorder for MockTransferMiddlewareKeeper.
type MockTransferMiddlewareKeeperMockRecorder struct {
	mock *MockTransferMiddlewareKeeper
}

// NewMockTransferMiddlewareKeeper creates a new mock instance.
func NewMockTransferMiddlewareKeeper(ctrl *gomock.Controller) *MockTransferMiddlewareKeeper {
	mock := &MockTransferMiddlewareKeeper{ctrl: ctrl}
	mock.recorder = &MockTransferMiddlewareKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferMiddlewareKeeper) EXPECT() *MockTransferMiddlewareKeeperMockRecorder {
	return m.recorder
}

// HasParachainIBCTokenInfoByNativeDenom mocks base method.
func (m *MockTransferMiddlewareKeeper) HasParachainIBCTokenInfoByNativeDenom(arg0 types.Context, arg1 string) (bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasParachainIBCTokenInfoByNativeDenom", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasParachainIBCTokenInfoByAssetID mocks base method.
func (m *MockTransferMiddlewareKeeper) HasParachainIBCTokenInfoByAssetID(arg0 types.Context, arg1 string) (bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasParachainIBCTokenInfoByAssetID", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasParachainIBCTokenInfoByAssetID indicates an expected call of HasParachainIBCTokenInfoByAssetID.
func (mr *MockTransferMiddlewareKeeperMockRecorder) HasParachainIBCTokenInfoByAssetID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasParachainIBCTokenInfoByAssetID", reflect.TypeOf((*MockTransferMiddlewareKeeper)(nil).HasParachainIBCTokenInfoByAssetID), arg0, arg1)
}


// GetParachainIBCTokenInfoByNativeDenom mocks base method.
func (m *MockTransferMiddlewareKeeper) GetParachainIBCTokenInfoByNativeDenom(arg0 types.Context, arg1 string) (pcktfrwdtypes.ParaChainIBCTokenInfo) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParachainIBCTokenInfoByNativeDenom", arg0, arg1)
	ret0, _ := ret[0].(pcktfrwdtypes.ParaChainIBCTokenInfo)
	return ret0
}

// GetParachainIBCTokenInfoByAssetID mocks base method.
func (m *MockTransferMiddlewareKeeper) GetParachainIBCTokenInfoByAssetID(arg0 types.Context, arg1 string) (pcktfrwdtypes.ParaChainIBCTokenInfo) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParachainIBCTokenInfoByAssetID", arg0, arg1)
	ret0, _ := ret[0].(pcktfrwdtypes.ParaChainIBCTokenInfo)
	return ret0
}